// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWSbKGW2OMF2mI96gzs_hFK2pfFvDPjag',
    appId: '1:248254015315:web:b9d8486b7584be4b1d23a6',
    messagingSenderId: '248254015315',
    projectId: 'test-firestore-v2',
    authDomain: 'test-firestore-v2.firebaseapp.com',
    databaseURL: 'https://test-firestore-v2-default-rtdb.firebaseio.com',
    storageBucket: 'test-firestore-v2.appspot.com',
    measurementId: 'G-XEBGST0Y87',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgN1rUgV6evZvFqIi3Kbp7BEDzYVZKS9s',
    appId: '1:248254015315:ios:2c4ae1a56d55d8321d23a6',
    messagingSenderId: '248254015315',
    projectId: 'test-firestore-v2',
    databaseURL: 'https://test-firestore-v2-default-rtdb.firebaseio.com',
    storageBucket: 'test-firestore-v2.appspot.com',
    iosBundleId: 'com.example.basicFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgN1rUgV6evZvFqIi3Kbp7BEDzYVZKS9s',
    appId: '1:248254015315:ios:2c4ae1a56d55d8321d23a6',
    messagingSenderId: '248254015315',
    projectId: 'test-firestore-v2',
    databaseURL: 'https://test-firestore-v2-default-rtdb.firebaseio.com',
    storageBucket: 'test-firestore-v2.appspot.com',
    iosBundleId: 'com.example.basicFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWSbKGW2OMF2mI96gzs_hFK2pfFvDPjag',
    appId: '1:248254015315:web:5ed4caa11931dc811d23a6',
    messagingSenderId: '248254015315',
    projectId: 'test-firestore-v2',
    authDomain: 'test-firestore-v2.firebaseapp.com',
    databaseURL: 'https://test-firestore-v2-default-rtdb.firebaseio.com',
    storageBucket: 'test-firestore-v2.appspot.com',
    measurementId: 'G-Z5KXZCGSWH',
  );
}
