// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPF316Y0eC_9WH26rRhO-d6WcrkVkEGuw',
    appId: '1:609956530009:web:a102183f73489071f52e48',
    messagingSenderId: '609956530009',
    projectId: 'test-firestore-v3',
    authDomain: 'test-firestore-v3.firebaseapp.com',
    storageBucket: 'test-firestore-v3.appspot.com',
    measurementId: 'G-N2BVK642HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnvhPO97zBZkhfEmUOwLwoMzYhRxdB3J4',
    appId: '1:609956530009:android:888aa7bdab02c8eaf52e48',
    messagingSenderId: '609956530009',
    projectId: 'test-firestore-v3',
    storageBucket: 'test-firestore-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbepF-zS8tJTg6rwMwNaRBVkcqBYp5pfk',
    appId: '1:609956530009:ios:f0c066897f54bcc4f52e48',
    messagingSenderId: '609956530009',
    projectId: 'test-firestore-v3',
    storageBucket: 'test-firestore-v3.appspot.com',
    iosBundleId: 'com.example.basicFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbepF-zS8tJTg6rwMwNaRBVkcqBYp5pfk',
    appId: '1:609956530009:ios:f0c066897f54bcc4f52e48',
    messagingSenderId: '609956530009',
    projectId: 'test-firestore-v3',
    storageBucket: 'test-firestore-v3.appspot.com',
    iosBundleId: 'com.example.basicFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPF316Y0eC_9WH26rRhO-d6WcrkVkEGuw',
    appId: '1:609956530009:web:96432d91d759e489f52e48',
    messagingSenderId: '609956530009',
    projectId: 'test-firestore-v3',
    authDomain: 'test-firestore-v3.firebaseapp.com',
    storageBucket: 'test-firestore-v3.appspot.com',
    measurementId: 'G-JKX0LMTSGR',
  );

}